### ISSUE TITLE
vocabulary_controllerの修正

### ISSUE THREAD

**Issue by TaikiSakai** [TaikiSakai/langLog#20]
transactionの処理を修正

・Activerecord Transaction処理について
createとupdateメソッドにて使用
単語のバリデーションで例外が発生した場合は正常にレスポンスを返すことができるが、
roleのバリデーション失敗時は、modelから直接レスポンスが返ってきてしまう
→transaction内でfalseをreurnし、controllerからレスポンスを返せるようにしたい

**Comment by TaikiSakai** [comment]
Started POST "/api/v1/wordcard/cards/2d1d944c-ca92-469a-bc28-17151e2cde44/vocabularies/" for 192.168.65.1 at 2024-04-24 17:05:12 +0000
Processing by Api::V1::Wordcard::VocabulariesController#create as */*
  Parameters: {"vocabularies"=>[{"word"=>"test101", "meaning"=>"aaabccc", "role"=>["aaafe"]}, {"word"=>"test102", "meaning"=>"わわわnnnnnncccdddddd", "role"=>["oolplplplplplplplooo"]}], "card_uuid"=>"2d1d944c-ca92-469a-bc28-17151e2cde44", "vocabulary"=>{}}
  User Load (0.5ms)  SELECT `users`.* FROM `users` WHERE `users`.`uid` = 'test2@example.com' LIMIT 1
  ↳ config/initializers/rescue_json_parse_errrors.rb:8:in `call'
  Card Load (0.5ms)  SELECT `cards`.* FROM `cards` WHERE `cards`.`user_id` = 2 AND `cards`.`uuid` = '2d1d944c-ca92-469a-bc28-17151e2cde44' LIMIT 1
  ↳ app/controllers/api/v1/wordcard/vocabularies_controller.rb:52:in `set_card'
Unpermitted parameter: :role. Context: {  }
  TRANSACTION (0.2ms)  BEGIN
  ↳ app/models/vocabulary.rb:28:in `block (3 levels) in save_vocabulary_with_roles_test'
  Role Load (0.4ms)  SELECT `roles`.* FROM `roles` WHERE `roles`.`name` = 'aaafe' LIMIT 1
  ↳ app/models/vocabulary.rb:28:in `block (3 levels) in save_vocabulary_with_roles_test'
  Role Exists? (0.2ms)  SELECT 1 AS one FROM `roles` WHERE `roles`.`name` = 'aaafe' AND `roles`.`id` != 11 LIMIT 1
  ↳ app/models/vocabulary.rb:31:in `block (2 levels) in save_vocabulary_with_roles_test'
  Vocabulary Create (0.3ms)  INSERT INTO `vocabularies` (`uuid`, `word`, `meaning`, `card_id`, `created_at`, `updated_at`) VALUES ('71365cff-b614-432d-af7f-9bcfe0ec66dd', 'test101', 'aaabccc', 8, '2024-04-24 17:05:12.947173', '2024-04-24 17:05:12.947173')
  ↳ app/models/vocabulary.rb:31:in `block (2 levels) in save_vocabulary_with_roles_test'
  WordRole Create (0.3ms)  INSERT INTO `word_roles` (`vocabulary_id`, `role_id`, `created_at`, `updated_at`) VALUES (261, 11, '2024-04-24 17:05:12.949224', '2024-04-24 17:05:12.949224')
  ↳ app/models/vocabulary.rb:31:in `block (2 levels) in save_vocabulary_with_roles_test'
Unpermitted parameter: :role. Context: {  }
  Role Load (0.2ms)  SELECT `roles`.* FROM `roles` WHERE `roles`.`name` = 'oolplplplplplplplooo' LIMIT 1
  ↳ app/models/vocabulary.rb:28:in `block (3 levels) in save_vocabulary_with_roles_test'
  Role Exists? (0.2ms)  SELECT 1 AS one FROM `roles` WHERE `roles`.`name` = 'oolplplplplplplplooo' LIMIT 1
  ↳ app/models/vocabulary.rb:31:in `block (2 levels) in save_vocabulary_with_roles_test'
  TRANSACTION (1.6ms)  ROLLBACK
  ↳ app/models/vocabulary.rb:22:in `save_vocabulary_with_roles_test'
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.05ms)
  User Load (0.4ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 2 LIMIT 1
  ↳ config/initializers/rescue_json_parse_errrors.rb:8:in `call'
Completed 422 Unprocessable Entity in 26ms (Views: 0.5ms | ActiveRecord: 4.7ms | Allocations: 10171)


Started POST "/api/v1/wordcard/cards/2d1d944c-ca92-469a-bc28-17151e2cde44/vocabularies/" for 192.168.65.1 at 2024-04-24 17:05:36 +0000
Processing by Api::V1::Wordcard::VocabulariesController#create as */*
  Parameters: {"vocabularies"=>[{"word"=>"test101", "meaning"=>"aaabccc", "role"=>["aaafe"]}, {"word"=>"test102", "meaning"=>"わわわnnnnnncccdddddd", "role"=>["oolplplooo"]}], "card_uuid"=>"2d1d944c-ca92-469a-bc28-17151e2cde44", "vocabulary"=>{}}
  User Load (0.1ms)  SELECT `users`.* FROM `users` WHERE `users`.`uid` = 'test2@example.com' LIMIT 1
  ↳ config/initializers/rescue_json_parse_errrors.rb:8:in `call'
  Card Load (0.1ms)  SELECT `cards`.* FROM `cards` WHERE `cards`.`user_id` = 2 AND `cards`.`uuid` = '2d1d944c-ca92-469a-bc28-17151e2cde44' LIMIT 1
  ↳ app/controllers/api/v1/wordcard/vocabularies_controller.rb:52:in `set_card'
Unpermitted parameter: :role. Context: {  }
  TRANSACTION (0.1ms)  BEGIN
  ↳ app/models/vocabulary.rb:24:in `block (2 levels) in save_vocabulary_with_roles_test'
  Role Load (0.1ms)  SELECT `roles`.* FROM `roles` WHERE `roles`.`name` = 'aaafe' LIMIT 1
  ↳ app/models/vocabulary.rb:30:in `block (3 levels) in save_vocabulary_with_roles_test'
  Role Exists? (0.1ms)  SELECT 1 AS one FROM `roles` WHERE `roles`.`name` = 'aaafe' AND `roles`.`id` != 11 LIMIT 1
  ↳ app/models/vocabulary.rb:33:in `block (2 levels) in save_vocabulary_with_roles_test'
  Vocabulary Create (0.2ms)  INSERT INTO `vocabularies` (`uuid`, `word`, `meaning`, `card_id`, `created_at`, `updated_at`) VALUES ('2e32eb44-bfa8-473b-85c0-18d127f6c256', 'test101', 'aaabccc', 8, '2024-04-24 17:05:36.810701', '2024-04-24 17:05:36.810701')
  ↳ app/models/vocabulary.rb:33:in `block (2 levels) in save_vocabulary_with_roles_test'
  WordRole Create (0.1ms)  INSERT INTO `word_roles` (`vocabulary_id`, `role_id`, `created_at`, `updated_at`) VALUES (262, 11, '2024-04-24 17:05:36.811804', '2024-04-24 17:05:36.811804')
  ↳ app/models/vocabulary.rb:33:in `block (2 levels) in save_vocabulary_with_roles_test'
Unpermitted parameter: :role. Context: {  }
  Role Load (0.1ms)  SELECT `roles`.* FROM `roles` WHERE `roles`.`name` = 'oolplplooo' LIMIT 1
  ↳ app/models/vocabulary.rb:30:in `block (3 levels) in save_vocabulary_with_roles_test'
  Role Exists? (0.1ms)  SELECT 1 AS one FROM `roles` WHERE `roles`.`name` = 'oolplplooo' LIMIT 1
  ↳ app/models/vocabulary.rb:33:in `block (2 levels) in save_vocabulary_with_roles_test'
  Vocabulary Create (0.1ms)  INSERT INTO `vocabularies` (`uuid`, `word`, `meaning`, `card_id`, `created_at`, `updated_at`) VALUES ('3076fe02-a4dc-420d-aaf6-55f97fef41a4', 'test102', 'わわわnnnnnncccdddddd', 8, '2024-04-24 17:05:36.815124', '2024-04-24 17:05:36.815124')
  ↳ app/models/vocabulary.rb:33:in `block (2 levels) in save_vocabulary_with_roles_test'
  Role Exists? (0.1ms)  SELECT 1 AS one FROM `roles` WHERE `roles`.`name` = 'oolplplooo' LIMIT 1
  ↳ app/models/vocabulary.rb:33:in `block (2 levels) in save_vocabulary_with_roles_test'
  Role Create (0.1ms)  INSERT INTO `roles` (`name`, `created_at`, `updated_at`) VALUES ('oolplplooo', '2024-04-24 17:05:36.816701', '2024-04-24 17:05:36.816701')
  ↳ app/models/vocabulary.rb:33:in `block (2 levels) in save_vocabulary_with_roles_test'
  WordRole Create (0.1ms)  INSERT INTO `word_roles` (`vocabulary_id`, `role_id`, `created_at`, `updated_at`) VALUES (263, 18, '2024-04-24 17:05:36.817671', '2024-04-24 17:05:36.817671')
  ↳ app/models/vocabulary.rb:33:in `block (2 levels) in save_vocabulary_with_roles_test'
  TRANSACTION (2.2ms)  COMMIT
  ↳ app/models/vocabulary.rb:22:in `save_vocabulary_with_roles_test'
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.04ms)
  User Load (0.1ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 2 LIMIT 1
  ↳ config/initializers/rescue_json_parse_errrors.rb:8:in `call'
Completed 200 OK in 81ms (Views: 0.8ms | ActiveRecord: 8.3ms | Allocations: 32773)
